"""Provider-neutral Agent Runtime R0/R1."""

from .protocols import Executor, Reasoner, Validator
from .records import (
    ActionObservation,
    ActionRequest,
    EnvironmentObservation,
    GoalContract,
    Plan,
    PlanStep,
    RunIdentity,
    RunTerminalState,
    ValidationResult,
)
from .runtime import AgentRuntime, RuntimeErrorState
from .actions import (
    ActionExecutionError,
    ActionKind,
    ApprovalClass,
    CrashInjected,
    ExecutionPacket,
    LocalWorkspaceExecutor,
    RollbackClass,
    WorkspacePolicy,
    WorkspaceViolation,
)
from .control import (
    ActionJournal,
    ApprovalDecisionR1,
    ApprovalRequestR1,
    ApprovalStore,
    ExecutionLease,
    LeaseStore,
)
from .r1_runtime import AgentRuntimeR1, R1RunSpec, RuntimeR1Error
from .transport import (
    AdversarialGatewayAdapter,
    GatewayError,
    GatewayReasonerAdapter,
    GatewayRequest,
    GatewayResponse,
    JsonlReasonerTransport,
    ReasonerGateway,
    ReasonerRequest,
    ReasonerResponse,
    ScriptedGatewayAdapter,
    ScriptedReasoner,
    SubprocessReasonerAdapter,
)
from .pack_registry import CapabilityRoute, LoadedPack, PackBus, PackLoader, PackManifest, PackRegistry, PackRegistryError
from .memory import MemoryEntry, MemoryStoreError, OperationalMemoryStore
from .supervisor import ChildRunSpec, EpisodeBudget, EpisodeSpec, Supervisor, SupervisorError
from .profile import ProfileProjection, ProfileProjectionError, apply_profiles_to_episode, load_profile_registry, project_profile, select_packs
from .routing import PackActionProvenance, PackAwareRouter, PackRoutingError, PackValidationReceipt
from .executor_health import ExecutorCapabilityLease, ExecutorHealthError, ExecutorHealthStore, ExecutorLeaseUnavailable
from .queue_control import QueueAdmissionError, QueueControlError, QueueItem, QueueNotDispatchable, WorkQueue
from .dispatch_reconciliation import DispatchConflict, DispatchEnvelope, DispatchError, DispatchProgress, DispatchReceipt, DispatchRecord, DurableDispatchStore
from .concurrent_memory import ConcurrentOperationalMemoryStore, MemoryCASConflict, MemoryDuplicateConflict, MemoryR2Error, MemoryRecord
from .driver_console import DRIVER_CONSOLE_SCHEMA, DriverConsoleError, build_driver_snapshot, render_driver_console
from .durability import CanonicalSnapshot, CanonicalSnapshotStore, DurabilityError, SNAPSHOT_SCHEMA, SNAPSHOT_SCHEMA_EPOCH, SnapshotIntegrityError, SnapshotNamespaceError

__all__ = [
    "ActionObservation",
    "ActionRequest",
    "AgentRuntime",
    "EnvironmentObservation",
    "Executor",
    "GoalContract",
    "Plan",
    "PlanStep",
    "Reasoner",
    "RunIdentity",
    "RunTerminalState",
    "RuntimeErrorState",
    "ValidationResult",
    "Validator",
    "ActionExecutionError",
    "ActionJournal",
    "ActionKind",
    "AgentRuntimeR1",
    "ApprovalClass",
    "ApprovalDecisionR1",
    "ApprovalRequestR1",
    "ApprovalStore",
    "CrashInjected",
    "ExecutionLease",
    "ExecutionPacket",
    "JsonlReasonerTransport",
    "AdversarialGatewayAdapter",
    "GatewayError",
    "GatewayReasonerAdapter",
    "GatewayRequest",
    "GatewayResponse",
    "ReasonerGateway",
    "LeaseStore",
    "LocalWorkspaceExecutor",
    "R1RunSpec",
    "ReasonerRequest",
    "ReasonerResponse",
    "RollbackClass",
    "RuntimeR1Error",
    "ScriptedReasoner",
    "ScriptedGatewayAdapter",
    "SubprocessReasonerAdapter",
    "WorkspacePolicy",
    "WorkspaceViolation",
    "CapabilityRoute",
    "LoadedPack",
    "PackBus",
    "PackLoader",
    "PackManifest",
    "PackRegistry",
    "PackRegistryError",
    "MemoryEntry",
    "MemoryStoreError",
    "OperationalMemoryStore",
    "ChildRunSpec",
    "EpisodeBudget",
    "EpisodeSpec",
    "Supervisor",
    "SupervisorError",
    "ProfileProjection",
    "ProfileProjectionError",
    "apply_profiles_to_episode",
    "load_profile_registry",
    "project_profile",
    "select_packs",
    "PackActionProvenance",
    "PackAwareRouter",
    "PackRoutingError",
    "PackValidationReceipt",
    "ExecutorCapabilityLease",
    "ExecutorHealthError",
    "ExecutorHealthStore",
    "ExecutorLeaseUnavailable",
    "QueueAdmissionError",
    "QueueControlError",
    "QueueItem",
    "QueueNotDispatchable",
    "WorkQueue",
    "DispatchConflict",
    "DispatchEnvelope",
    "DispatchError",
    "DispatchProgress",
    "DispatchReceipt",
    "DispatchRecord",
    "DurableDispatchStore",
    "ConcurrentOperationalMemoryStore",
    "MemoryCASConflict",
    "MemoryDuplicateConflict",
    "MemoryR2Error",
    "MemoryRecord",
    "DRIVER_CONSOLE_SCHEMA",
    "DriverConsoleError",
    "build_driver_snapshot",
    "render_driver_console",
    "CanonicalSnapshot",
    "CanonicalSnapshotStore",
    "DurabilityError",
    "SNAPSHOT_SCHEMA",
    "SNAPSHOT_SCHEMA_EPOCH",
    "SnapshotIntegrityError",
    "SnapshotNamespaceError",
]
