"""Provider-neutral Agent Runtime R0/R1."""

from .protocols import Executor, Reasoner, Validator
from .records import (
    ActionObservation,
    ActionRequest,
    EnvironmentObservation,
    GoalContract,
    Plan,
    PlanStep,
    RunIdentity,
    RunTerminalState,
    ValidationResult,
)
from .runtime import AgentRuntime, RuntimeErrorState
from .actions import (
    ActionExecutionError,
    ActionKind,
    ApprovalClass,
    CrashInjected,
    ExecutionPacket,
    LocalWorkspaceExecutor,
    RollbackClass,
    WorkspacePolicy,
    WorkspaceViolation,
)
from .control import (
    ActionJournal,
    ApprovalDecisionR1,
    ApprovalRequestR1,
    ApprovalStore,
    ExecutionLease,
    LeaseStore,
)
from .r1_runtime import AgentRuntimeR1, R1RunSpec, RuntimeR1Error
from .transport import (
    AdversarialGatewayAdapter,
    GatewayError,
    GatewayReasonerAdapter,
    GatewayRequest,
    GatewayResponse,
    JsonlReasonerTransport,
    ReasonerGateway,
    ReasonerRequest,
    ReasonerResponse,
    ScriptedGatewayAdapter,
    ScriptedReasoner,
    SubprocessReasonerAdapter,
)
from .pack_registry import CapabilityRoute, LoadedPack, PackBus, PackLoader, PackManifest, PackRegistry, PackRegistryError
from .memory import MemoryEntry, MemoryStoreError, OperationalMemoryStore
from .supervisor import ChildRunSpec, EpisodeBudget, EpisodeSpec, Supervisor, SupervisorError
from .profile import ProfileProjection, ProfileProjectionError, apply_profiles_to_episode, load_profile_registry, project_profile, select_packs
from .routing import PackActionProvenance, PackAwareRouter, PackRoutingError, PackValidationReceipt
from .executor_health import ExecutorCapabilityLease, ExecutorHealthError, ExecutorHealthStore, ExecutorLeaseUnavailable
from .queue_control import QueueAdmissionError, QueueControlError, QueueItem, QueueNotDispatchable, WorkQueue
from .dispatch_reconciliation import DispatchConflict, DispatchEnvelope, DispatchError, DispatchProgress, DispatchReceipt, DispatchRecord, DurableDispatchStore
from .concurrent_memory import ConcurrentOperationalMemoryStore, MemoryCASConflict, MemoryDuplicateConflict, MemoryR2Error, MemoryRecord
from .driver_console import DRIVER_CONSOLE_SCHEMA, DRIVER_RECOVERY_SURFACE_SCHEMA, DriverConsoleError, build_driver_snapshot, build_driver_recovery_surface, render_driver_console, render_driver_recovery_surface
from .durability import CanonicalSnapshot, CanonicalSnapshotStore, CompactionPolicy, CompactionReceipt, COMPACTION_SCHEMA, DurabilityCompactor, DurabilityError, SNAPSHOT_SCHEMA, SNAPSHOT_SCHEMA_EPOCH, SnapshotChainStore, SnapshotIntegrityError, SnapshotNamespaceError
from .migration import APPLIED, DRY_RUN, FORBIDDEN, LOSSY_REQUIRES_APPROVAL, MIGRATION_RECEIPT_SCHEMA, MIGRATION_SCHEMA, MigrationError, MigrationExecutionError, MigrationPathError, MigrationReceipt, MigrationRegistry, MigrationResult, MigrationRule, ForbiddenMigrationError, LossyDowngradeRequiresApproval, ROLLED_BACK, StateMigrator, UnknownEpochError
from .soft_governance_durability import ADVISORY_STATUSES, SOFT_SCHEMA, SoftGovernanceDurabilityError, migrate_soft_state, soft_state_digest, validate_soft_state
from .namespace import DELEGATION_STATES, NAMESPACE_SCHEMA, PRINCIPAL_TYPES, DelegationGrant, NamespaceBinding, NamespaceGuard, NamespaceIsolationError, PrincipalIdentity, PrincipalRegistry, validate_relative_path
from .revocation import CapabilityGrant, DispatchAdmission, EFFECT_CLASSES, GRANT_STATES, REVOCATION_SCHEMA, RevocationDispatcher, RevocationError, RevocationEvent, RevocationStore, ZERO_REVOCATION_HASH
from .pack_lifecycle import ADVISORY_OVERLAY_ROLE, PACK_LIFECYCLE_SCHEMA, PACK_STATES, PackLifecycleError, PackLifecycleManager, PackLifecycleReceipt, PackLifecycleRecord, PackRunPin, advisory_overlay_record
from .executor_admission import ADMISSION_STATUSES, EXECUTOR_ADMISSION_SCHEMA, ExecutorAdmission, ExecutorAdmissionError, ExecutorAdmissionStore, ExecutorRouteDenied, HEALTH_STATUSES as ADMISSION_HEALTH_STATUSES, PERMISSION_CEILING, PRIVACY_BOUNDARIES
from .accounting import ACCOUNTING_DIMENSIONS, ACCOUNTING_EVENT_SCHEMA, ACCOUNTING_SCHEMA, AccountingDuplicate, AccountingError, AccountingEvent, AccountingPolicy, AccountingQuotaExceeded, AccountingStore, ATTEMPT_KINDS, BoundedFairScheduler, BudgetScope, CostVector, FairWorkItem, ReservationReceipt, SettlementReceipt
from .durable_memory import DURABLE_MEMORY_EPOCH, DURABLE_MEMORY_EVENT_SCHEMA, DURABLE_MEMORY_SCHEMA, DurableMemoryError, DurableMemoryEvent, DurableMemoryRecord, DurableOperationalMemoryStore, MemoryNamespaceDenied, MemorySnapshotIntegrityError, MEMORY_EVENT_TYPES, MEMORY_STATES
from .recovery import DELIVERY_SEMANTICS, FAULT_POINTS, RECOVERY_PHASES, RECOVERY_SCHEMA, RecoveryBlocked, RecoveryError, RecoveryFaultInjected, RecoveryFaultMatrix, RecoveryOrchestrator, RecoveryPhase
from .dr_bundle import DR_BUNDLE_EPOCH, DR_BUNDLE_SCHEMA, DRBundleError, DRBundleIntegrityError, RecoveryBundleBuilder, RecoveryBundleVerifier, REQUIRED_CHUNKS
from .adversarial import ADVERSARIAL_SCHEMA, ALLOWED_OUTCOMES, AdversarialCase, AdversarialMatrix, AdversarialMatrixError, REQUIRED_CASE_IDS

__all__ = [
    "ActionObservation",
    "ActionRequest",
    "AgentRuntime",
    "EnvironmentObservation",
    "Executor",
    "GoalContract",
    "Plan",
    "PlanStep",
    "Reasoner",
    "RunIdentity",
    "RunTerminalState",
    "RuntimeErrorState",
    "ValidationResult",
    "Validator",
    "ActionExecutionError",
    "ActionJournal",
    "ActionKind",
    "AgentRuntimeR1",
    "ApprovalClass",
    "ApprovalDecisionR1",
    "ApprovalRequestR1",
    "ApprovalStore",
    "CrashInjected",
    "ExecutionLease",
    "ExecutionPacket",
    "JsonlReasonerTransport",
    "AdversarialGatewayAdapter",
    "GatewayError",
    "GatewayReasonerAdapter",
    "GatewayRequest",
    "GatewayResponse",
    "ReasonerGateway",
    "LeaseStore",
    "LocalWorkspaceExecutor",
    "R1RunSpec",
    "ReasonerRequest",
    "ReasonerResponse",
    "RollbackClass",
    "RuntimeR1Error",
    "ScriptedReasoner",
    "ScriptedGatewayAdapter",
    "SubprocessReasonerAdapter",
    "WorkspacePolicy",
    "WorkspaceViolation",
    "CapabilityRoute",
    "LoadedPack",
    "PackBus",
    "PackLoader",
    "PackManifest",
    "PackRegistry",
    "PackRegistryError",
    "MemoryEntry",
    "MemoryStoreError",
    "OperationalMemoryStore",
    "ChildRunSpec",
    "EpisodeBudget",
    "EpisodeSpec",
    "Supervisor",
    "SupervisorError",
    "ProfileProjection",
    "ProfileProjectionError",
    "apply_profiles_to_episode",
    "load_profile_registry",
    "project_profile",
    "select_packs",
    "PackActionProvenance",
    "PackAwareRouter",
    "PackRoutingError",
    "PackValidationReceipt",
    "ExecutorCapabilityLease",
    "ExecutorHealthError",
    "ExecutorHealthStore",
    "ExecutorLeaseUnavailable",
    "QueueAdmissionError",
    "QueueControlError",
    "QueueItem",
    "QueueNotDispatchable",
    "WorkQueue",
    "DispatchConflict",
    "DispatchEnvelope",
    "DispatchError",
    "DispatchProgress",
    "DispatchReceipt",
    "DispatchRecord",
    "DurableDispatchStore",
    "ConcurrentOperationalMemoryStore",
    "MemoryCASConflict",
    "MemoryDuplicateConflict",
    "MemoryR2Error",
    "MemoryRecord",
    "DRIVER_CONSOLE_SCHEMA",
    "DRIVER_RECOVERY_SURFACE_SCHEMA",
    "DriverConsoleError",
    "build_driver_snapshot",
    "render_driver_console",
    "build_driver_recovery_surface",
    "render_driver_recovery_surface",
    "CanonicalSnapshot",
    "CanonicalSnapshotStore",
    "DurabilityError",
    "SNAPSHOT_SCHEMA",
    "SNAPSHOT_SCHEMA_EPOCH",
    "SnapshotIntegrityError",
    "SnapshotNamespaceError",
    "CompactionPolicy",
    "CompactionReceipt",
    "COMPACTION_SCHEMA",
    "DurabilityCompactor",
    "SnapshotChainStore",
    "APPLIED",
    "DRY_RUN",
    "FORBIDDEN",
    "LOSSY_REQUIRES_APPROVAL",
    "MIGRATION_RECEIPT_SCHEMA",
    "MIGRATION_SCHEMA",
    "MigrationError",
    "MigrationExecutionError",
    "MigrationPathError",
    "MigrationReceipt",
    "MigrationRegistry",
    "MigrationResult",
    "MigrationRule",
    "ForbiddenMigrationError",
    "LossyDowngradeRequiresApproval",
    "ROLLED_BACK",
    "StateMigrator",
    "UnknownEpochError",
    "ADVISORY_STATUSES",
    "SOFT_SCHEMA",
    "SoftGovernanceDurabilityError",
    "migrate_soft_state",
    "soft_state_digest",
    "validate_soft_state",
    "DELEGATION_STATES",
    "NAMESPACE_SCHEMA",
    "PRINCIPAL_TYPES",
    "DelegationGrant",
    "NamespaceBinding",
    "NamespaceGuard",
    "NamespaceIsolationError",
    "PrincipalIdentity",
    "PrincipalRegistry",
    "validate_relative_path",
    "CapabilityGrant",
    "DispatchAdmission",
    "EFFECT_CLASSES",
    "GRANT_STATES",
    "REVOCATION_SCHEMA",
    "RevocationDispatcher",
    "RevocationError",
    "RevocationEvent",
    "RevocationStore",
    "ZERO_REVOCATION_HASH",
    "ADVISORY_OVERLAY_ROLE",
    "PACK_LIFECYCLE_SCHEMA",
    "PACK_STATES",
    "PackLifecycleError",
    "PackLifecycleManager",
    "PackLifecycleReceipt",
    "PackLifecycleRecord",
    "PackRunPin",
    "advisory_overlay_record",
    "ADMISSION_STATUSES",
    "EXECUTOR_ADMISSION_SCHEMA",
    "ExecutorAdmission",
    "ExecutorAdmissionError",
    "ExecutorAdmissionStore",
    "ExecutorRouteDenied",
    "ADMISSION_HEALTH_STATUSES",
    "PERMISSION_CEILING",
    "PRIVACY_BOUNDARIES",
    "ACCOUNTING_DIMENSIONS",
    "ACCOUNTING_EVENT_SCHEMA",
    "ACCOUNTING_SCHEMA",
    "AccountingDuplicate",
    "AccountingError",
    "AccountingEvent",
    "AccountingPolicy",
    "AccountingQuotaExceeded",
    "AccountingStore",
    "ATTEMPT_KINDS",
    "BoundedFairScheduler",
    "BudgetScope",
    "CostVector",
    "FairWorkItem",
    "ReservationReceipt",
    "SettlementReceipt",
    "DURABLE_MEMORY_EPOCH",
    "DURABLE_MEMORY_EVENT_SCHEMA",
    "DURABLE_MEMORY_SCHEMA",
    "DurableMemoryError",
    "DurableMemoryEvent",
    "DurableMemoryRecord",
    "DurableOperationalMemoryStore",
    "MemoryNamespaceDenied",
    "MemorySnapshotIntegrityError",
    "MEMORY_EVENT_TYPES",
    "MEMORY_STATES",
    "DELIVERY_SEMANTICS",
    "FAULT_POINTS",
    "RECOVERY_PHASES",
    "RECOVERY_SCHEMA",
    "RecoveryBlocked",
    "RecoveryError",
    "RecoveryFaultInjected",
    "RecoveryFaultMatrix",
    "RecoveryOrchestrator",
    "RecoveryPhase",
    "DR_BUNDLE_EPOCH",
    "DR_BUNDLE_SCHEMA",
    "DRBundleError",
    "DRBundleIntegrityError",
    "RecoveryBundleBuilder",
    "RecoveryBundleVerifier",
    "REQUIRED_CHUNKS",
    "ADVERSARIAL_SCHEMA",
    "ALLOWED_OUTCOMES",
    "AdversarialCase",
    "AdversarialMatrix",
    "AdversarialMatrixError",
    "REQUIRED_CASE_IDS",
]
