"""Minimal REOS vNext R1 research-execution control kernel."""

from .contract import (
    ActivationDecision,
    ArtifactRefRecord,
    ClaimCandidate,
    EvidenceRequest,
    HandoffBundle,
    QuestionContract,
    ResearchCase,
    ResearchObligation,
    ReviewDecision,
    ReviewRequest,
)
from .kernel import (
    add_obligation,
    amend_question,
    compute_case_status,
    load_case,
    new_case,
    prepare_handoff,
    record_artifact,
    record_claim_candidate,
    record_evidence_request,
    record_review,
    request_review,
    save_case,
    serialize_case,
    set_case_state,
    status_snapshot,
)
from .validation import ContractError, canonical_json, collect_case_errors, sha256_json, validate_case, validate_handoff

__all__ = [
    "ActivationDecision",
    "ArtifactRefRecord",
    "ClaimCandidate",
    "EvidenceRequest",
    "HandoffBundle",
    "QuestionContract",
    "ResearchCase",
    "ResearchObligation",
    "ReviewDecision",
    "ReviewRequest",
    "ContractError",
    "add_obligation",
    "amend_question",
    "canonical_json",
    "collect_case_errors",
    "compute_case_status",
    "load_case",
    "new_case",
    "prepare_handoff",
    "record_artifact",
    "record_claim_candidate",
    "record_evidence_request",
    "record_review",
    "request_review",
    "save_case",
    "serialize_case",
    "set_case_state",
    "sha256_json",
    "status_snapshot",
    "validate_case",
    "validate_handoff",
]
