"""Deep Research Capability — record constructors & validators (Round 1).

Wraps the inherited Research OS kernel authorities so the 13 Deep Research
Capability records are constructed and validated consistently with the kernel,
without duplicating vocabulary or authority.

Key design points (per TASK.md Round 1 / Qwen Round 1 lesson — canonical
outputs beat hand-edits, and re-use-not-duplicate):

* The 13 JSON Schemas are GENERATED by ``generate_schemas.py``; this module
  loads and validates against them. Never hand-edit the emitted JSON.
* The executor-observation contract delegates the prohibited-key / required
  field enforcement to ``research_os.executor_contract.validate_return`` — the
  kernel is the single authority for "an executor may never self-approve, mark
  complete, or raise a claim ceiling".
* Every record field is explicitly classified by ORIGIN so downstream code and
  tests can prove the executor never writes an owner/GPT-adjudicated field and
  never smuggles a prohibited key.

Run from the repository root:
    python3 tools/deep_research/records.py   # self smoke-test
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "schemas" / "deep-research"

# Field-origin categories -----------------------------------------------------
DETERMINISTIC = "deterministic"          # kernel / OS computed (ids, shas, facts derived by OS)
EXECUTOR_PROPOSED = "executor_proposed"  # written by the executor under contract
OWNER_ADJUDICATED = "owner_adjudicated"  # requires an explicit GPT/owner decision
KERNEL_ENUM = "kernel_enum"              # value drawn from a kernel vocabulary
PROHIBITED = "prohibited"                # executor is forbidden from ever writing this

_SCHEMA_CACHE: dict[str, dict] = {}


def load_schema(name: str) -> dict:
    """Load a generated deep-research schema by record name (fail-closed)."""
    if name in _SCHEMA_CACHE:
        return _SCHEMA_CACHE[name]
    path = SCHEMA_DIR / f"{name}.schema.json"
    if not path.exists():
        raise FileNotFoundError(
            f"schema '{name}' not found at {path}; run generate_schemas.py first"
        )
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    _SCHEMA_CACHE[name] = data
    return data


def validate_record(name: str, obj: Any) -> Any:
    """Validate ``obj`` against the generated schema for ``name`` (fail-closed).

    Raises ``ValueError`` with collected messages on any schema violation.
    Unknown/extra properties are rejected (additionalProperties: False).
    """
    if not isinstance(obj, dict):
        raise ValueError(f"record '{name}' must be a JSON object")
    schema = load_schema(name)
    try:
        import jsonschema  # type: ignore
    except Exception:
        # jsonschema missing — at minimum enforce required fields structurally.
        missing = [f for f in schema.get("required", []) if f not in obj]
        if missing:
            raise ValueError(f"record '{name}' missing required fields: {missing}")
        return obj
    validator = jsonschema.Draft202012Validator(schema)
    errors = [f"{list(e.path)}: {e.message}" for e in validator.iter_errors(obj)]
    if errors:
        raise ValueError(
            f"record '{name}' failed schema validation:\n  " + "\n  ".join(errors)
        )
    return obj


# Executor-observation: delegate to the kernel contract ------------------------
def validate_executor_observation(obj: Any) -> Any:
    """Enforce the Research OS executor-return contract, then the deep-research
    structural schema. The kernel is the authority for prohibited keys and the
    seven required return fields; the deep-research schema adds observation_id /
    action_id and the fail-closed ``if/then`` rules."""
    if not isinstance(obj, dict):
        raise ValueError("executor-observation must be a JSON object")
    sys.path.insert(0, str(REPO_ROOT / "tools"))
    from research_os.executor_contract import validate_return  # type: ignore

    # Kernel enforces required return fields + prohibited keys (self_approved,
    # mark_episode_complete, claim_ceiling). strict_schema=False here because the
    # deep-research observation carries extra keys the kernel schema omits.
    validate_return(obj, strict_schema=False)
    return validate_record("executor-observation", obj)


# Explicit per-record field-origin classification ------------------------------
# Category per (record, field). Anything not listed defaults to EXECUTOR_PROPOSED
# only when explicitly allowed; unknown fields are rejected by the schema anyway.
_ORIGIN: dict[str, dict[str, str]] = {
    "research-topic-candidate": {
        "candidate_id": DETERMINISTIC,
        "proposed_question": EXECUTOR_PROPOSED,
        "proposed_scope": EXECUTOR_PROPOSED,
        "source_of_seed": EXECUTOR_PROPOSED,
        "materiality": EXECUTOR_PROPOSED,
        "expected_information_gain": EXECUTOR_PROPOSED,
        "tractability": EXECUTOR_PROPOSED,
        "access": EXECUTOR_PROPOSED,
        "freshness": EXECUTOR_PROPOSED,
        "cost": EXECUTOR_PROPOSED,
        "risk": EXECUTOR_PROPOSED,
        "diversity": EXECUTOR_PROPOSED,
        "proposed_strategy_pack": EXECUTOR_PROPOSED,
        "status": OWNER_ADJUDICATED,  # SELECTED/REJECTED are owner decisions
        "provenance": EXECUTOR_PROPOSED,
    },
    "research-brief": {
        "brief_id": DETERMINISTIC,
        "question_version": OWNER_ADJUDICATED,
        "question": OWNER_ADJUDICATED,
        "scope": OWNER_ADJUDICATED,
        "strategy_pack": OWNER_ADJUDICATED,
        "source_family_priorities": OWNER_ADJUDICATED,
        "frozen": DETERMINISTIC,
        "created_at": DETERMINISTIC,
        "provenance": OWNER_ADJUDICATED,
    },
    "research-plan": {
        "plan_id": DETERMINISTIC,
        "brief_id": DETERMINISTIC,
        "obligations": EXECUTOR_PROPOSED,
        "subquestions": EXECUTOR_PROPOSED,
        "search_strategy": EXECUTOR_PROPOSED,
        "stop_criteria": OWNER_ADJUDICATED,
        "created_at": DETERMINISTIC,
    },
    "evidence-obligation": {
        "obligation_id": DETERMINISTIC,
        "claim_id": DETERMINISTIC,
        "obligation_class": KERNEL_ENUM,
        "status": DETERMINISTIC,  # kernel-enforced transitions
        "severity": EXECUTOR_PROPOSED,
        "required_source_family": EXECUTOR_PROPOSED,
        "satisfied_by": DETERMINISTIC,
        "ceiling_impact": OWNER_ADJUDICATED,  # ceiling changes are OS/gate decisions
        "notes": EXECUTOR_PROPOSED,
    },
    "source-record": {
        "source_id": DETERMINISTIC,
        "kind": EXECUTOR_PROPOSED,
        "source_family": EXECUTOR_PROPOSED,
        "discovery_method": EXECUTOR_PROPOSED,
        "opened": EXECUTOR_PROPOSED,
        "access_level": EXECUTOR_PROPOSED,
        "inspected_scope": EXECUTOR_PROPOSED,
        "claimed_vs_actual_scope": EXECUTOR_PROPOSED,
        "opened_at": EXECUTOR_PROPOSED,
        "independence_group": EXECUTOR_PROPOSED,
        "trust_flags": EXECUTOR_PROPOSED,
        "provenance": EXECUTOR_PROPOSED,
    },
    "research-action": {
        "action_id": DETERMINISTIC,
        "action_code": KERNEL_ENUM,
        "objective": EXECUTOR_PROPOSED,
        "inputs": EXECUTOR_PROPOSED,
        "expected_output": EXECUTOR_PROPOSED,
        "prohibited_claims": EXECUTOR_PROPOSED,
        "budget": EXECUTOR_PROPOSED,
        "stop_condition": EXECUTOR_PROPOSED,
    },
    "executor-observation": {
        "observation_id": DETERMINISTIC,
        "action_id": DETERMINISTIC,
        "observations": EXECUTOR_PROPOSED,
        "source_identities": EXECUTOR_PROPOSED,
        "access_level": EXECUTOR_PROPOSED,
        "calculation_result": EXECUTOR_PROPOSED,
        "errors": EXECUTOR_PROPOSED,
        "provenance": EXECUTOR_PROPOSED,
        "timestamps": DETERMINISTIC,
        # The three prohibited keys — an executor is forbidden from writing these.
        "self_approved": PROHIBITED,
        "mark_episode_complete": PROHIBITED,
        "claim_ceiling": PROHIBITED,
    },
    "claim-evidence-record": {
        "claim_id": DETERMINISTIC,
        "claim_text": EXECUTOR_PROPOSED,
        "claim_ceiling": OWNER_ADJUDICATED,  # ceiling is a gate/owner decision
        "supporting_obligations": DETERMINISTIC,
        "source_relations": EXECUTOR_PROPOSED,
        "entailed_by_source": EXECUTOR_PROPOSED,
        "faithfulness": EXECUTOR_PROPOSED,
        "groundedness": EXECUTOR_PROPOSED,
        "status": OWNER_ADJUDICATED,  # ACCEPTED/REJECTED are owner/GPT decisions
    },
    "research-trace-event": {
        "event_id": DETERMINISTIC,
        "timestamp": DETERMINISTIC,
        "type": DETERMINISTIC,
        "actor": DETERMINISTIC,
        "payload_sha256": DETERMINISTIC,
        "round": DETERMINISTIC,
        "phase": DETERMINISTIC,
    },
    "research-sufficiency-decision": {
        "decision_id": DETERMINISTIC,
        "episode_id": DETERMINISTIC,
        "hard_gates_passed": DETERMINISTIC,  # kernel-computed
        "failed_hard_gates": DETERMINISTIC,
        "sufficiency_vector": EXECUTOR_PROPOSED,  # model proposes the vector
        "decision": OWNER_ADJUDICATED,  # final stop is gate/owner adjudicated
        "rationale": EXECUTOR_PROPOSED,
        "deterministic_inputs": DETERMINISTIC,
        "model_proposed": EXECUTOR_PROPOSED,
    },
    "research-episode-result": {
        "result_id": DETERMINISTIC,
        "episode_id": DETERMINISTIC,
        "brief_id": DETERMINISTIC,
        "final_state": KERNEL_ENUM,
        "claims": EXECUTOR_PROPOSED,
        "source_records": EXECUTOR_PROPOSED,
        "obligations_status": DETERMINISTIC,
        "sufficiency_decision": EXECUTOR_PROPOSED,
        "report_ref": DETERMINISTIC,
        "machine_trace_ref": DETERMINISTIC,
        "created_at": DETERMINISTIC,
    },
    "research-queue-item": {
        "queue_item_id": DETERMINISTIC,
        "topic_candidate": EXECUTOR_PROPOSED,
        "brief": OWNER_ADJUDICATED,
        "episode_id": DETERMINISTIC,
        "lease": EXECUTOR_PROPOSED,
        "status": KERNEL_ENUM,
        "checkpoint_commit": DETERMINISTIC,
        "priority_factors": EXECUTOR_PROPOSED,
        "created_at": DETERMINISTIC,
    },
    "research-campaign": {
        "campaign_id": DETERMINISTIC,
        "items": EXECUTOR_PROPOSED,
        "stop_conditions": OWNER_ADJUDICATED,
        "status": KERNEL_ENUM,
        "created_at": DETERMINISTIC,
    },
}


def field_origin(record: str, field: str) -> str:
    """Return the ORIGIN category for ``field`` of ``record``.

    Falls back to EXECUTOR_PROPOSED for unlisted-but-schema-known fields (they
    are executor-writable by default), and PROHIBITED only where explicitly
    declared. Raises ValueError for fields absent from the schema entirely.
    """
    schema = load_schema(record)
    if field not in schema.get("properties", {}):
        raise ValueError(f"field '{field}' is not part of record '{record}'")
    return _ORIGIN.get(record, {}).get(field, EXECUTOR_PROPOSED)


def list_records() -> list[str]:
    return sorted(
        p.stem.replace(".schema", "")
        for p in SCHEMA_DIR.glob("*.schema.json")
    )


# Constructors ----------------------------------------------------------------
# Each constructor merges typed defaults with caller overrides, then validates
# against the schema (fail-closed). Overrides are restricted to known schema
# properties — unknown kwargs raise (no silent extra fields, since the schemas
# are additionalProperties: False).
_DEFAULTS: dict[str, dict] = {
    "research-topic-candidate": {
        "candidate_id": "cand-000",
        "proposed_question": "unfrozen question",
        "source_of_seed": "PROJECT_GAP",
        "proposed_strategy_pack": "default",
        "status": "CANDIDATE",
    },
    "research-brief": {
        "brief_id": "brief-000",
        "question_version": "v1",
        "question": "unfrozen question",
        "scope": {
            "population": "unspecified",
            "object": "unspecified",
            "timeframe": "unspecified",
            "outcomes": [],
        },
        "strategy_pack": "default",
        "frozen": True,
    },
    "research-plan": {
        "plan_id": "plan-000",
        "brief_id": "brief-000",
        "obligations": [],
    },
    "evidence-obligation": {
        "obligation_id": "obl-000",
        "claim_id": "claim-000",
        "obligation_class": "PRIMARY_SOURCE",
        "status": "OPEN",
    },
    "source-record": {
        "source_id": "src-000",
        "access_level": "DISCOVERED",
    },
    "research-action": {
        "action_id": "act-000",
        "action_code": "SEARCH_PRIMARY_SOURCE",
    },
    "executor-observation": {
        "observation_id": "obs-000",
        "action_id": "act-000",
        "observations": [],
        "source_identities": [],
        "access_level": "DISCOVERED",
        "calculation_result": None,
        "errors": [],
        "provenance": [],
        "timestamps": {},
    },
    "claim-evidence-record": {
        "claim_id": "claim-000",
        "claim_text": "candidate claim",
        "claim_ceiling": "TENTATIVE",
        "source_relations": [],
    },
    "research-trace-event": {
        "event_id": "evt-000",
        "timestamp": "2026-01-01T00:00:00Z",
        "type": "STEP",
        "actor": "kernel",
        "payload_sha256": "0" * 64,
    },
    "research-sufficiency-decision": {
        "decision_id": "suff-000",
        "episode_id": "ep-000",
        "decision": "CONTINUE_RESEARCH",
    },
    "research-episode-result": {
        "result_id": "res-000",
        "episode_id": "ep-000",
        "final_state": "CANDIDATE_COMPLETE",
    },
    "research-queue-item": {
        "queue_item_id": "qi-000",
        "status": "QUEUED",
    },
    "research-campaign": {
        "campaign_id": "camp-000",
        "stop_conditions": {"queue_empty_stops": True},
    },
}


def make_record(name: str, **overrides: Any) -> dict:
    """Construct a record of ``name`` from defaults + overrides, validate, return."""
    schema = load_schema(name)
    known = set(schema.get("properties", {}).keys())
    defaults = dict(_DEFAULTS.get(name, {}))
    merged = {**defaults, **overrides}
    unknown = [k for k in merged if k not in known]
    if unknown:
        raise ValueError(
            f"record '{name}' got unknown field(s) {unknown}; schema properties are {sorted(known)}"
        )
    return validate_record(name, merged)


# Human-friendly named constructors (thin wrappers over make_record) ----------
def make_topic_candidate(**o: Any) -> dict:
    return make_record("research-topic-candidate", **o)


def make_brief(**o: Any) -> dict:
    return make_record("research-brief", **o)


def make_plan(**o: Any) -> dict:
    return make_record("research-plan", **o)


def make_evidence_obligation(**o: Any) -> dict:
    return make_record("evidence-obligation", **o)


def make_source_record(**o: Any) -> dict:
    return make_record("source-record", **o)


def make_research_action(**o: Any) -> dict:
    return make_record("research-action", **o)


def make_executor_observation(**o: Any) -> dict:
    # The executor-observation contract is enforced by the kernel delegate below;
    # the generic path would also validate the structural schema.
    obj = make_record("executor-observation", **o)
    return validate_executor_observation(obj)


def make_claim_evidence_record(**o: Any) -> dict:
    return make_record("claim-evidence-record", **o)


def make_trace_event(**o: Any) -> dict:
    return make_record("research-trace-event", **o)


def make_sufficiency_decision(**o: Any) -> dict:
    return make_record("research-sufficiency-decision", **o)


def make_episode_result(**o: Any) -> dict:
    return make_record("research-episode-result", **o)


def make_queue_item(**o: Any) -> dict:
    return make_record("research-queue-item", **o)


def make_campaign(**o: Any) -> dict:
    return make_record("research-campaign", **o)


def _smoke() -> None:
    """Self smoke-test: build every record once; assert origin invariants."""
    for name in list_records():
        make_record(name)
    # Invariant: an executor-observation must never carry an owner-adjudicated or
    # prohibited field as a legitimately writable field (prohibited keys are the
    # only exceptions, and they must be classified PROHIBITED, not writable).
    for fld, cat in _ORIGIN.get("executor-observation", {}).items():
        assert cat in (DETERMINISTIC, EXECUTOR_PROPOSED, PROHIBITED), (
            f"executor-observation field {fld} has unexpected origin {cat}"
        )
    # claim_ceiling in claim-evidence-record is owner-adjudicated, never executor.
    assert field_origin("claim-evidence-record", "claim_ceiling") == OWNER_ADJUDICATED
    print(f"records.py smoke OK: {len(list_records())} records constructible")


if __name__ == "__main__":
    _smoke()
